name: build
on: [push, pull_request]
jobs:
    applications:
        name: application test suite
        runs-on: ubuntu-latest
        timeout-minutes: 30
        env:
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
        steps:
            -   uses: actions/checkout@v1
            -   uses: actions/setup-java@v1
                with:
                    java-version: '8.x'
            -   name: Package application
                run: |
                    chmod +x mvnw
                    ./mvnw -ntp package -DskipTests -e -U
#            - name: Verify application
#              run: ./mvnw -ntp clean verify
